os: Visual Studio 2017

install:
  - C:\msys64\usr\bin\bash -lc 'cd $APPVEYOR_BUILD_FOLDER; pacman -Syu --noconfirm; MINGW_INSTALLS=mingw64 makepkg-mingw -sLf --noconfirm'

build: off

artifacts:
  - path: '*.xz'